### ISSUE TITLE
count = count - (0.1*count)

### ISSUE THREAD

**Issue by wiheto** [shivam5992/textstat#10]
In syllable_count there is a "count = count - (0.1*count)" which will always make the syllable_count 10% smaller. So "Beautiful" returned 2.7. Is there a reason for this?

This function is called in polysyllabcount(), this will then only count syllables with more than 4 syllables in, which is not the definition of polysyllablecount

(I'm using python 3, I can't think of an immediate reason why this would just effect just python 3)

**Comment by creedrogers** [comment]
+1

I have the same question, and am using python 2.7.11

**Comment by wiheto** [comment]
Short story: 

I recomend removing the 0.1, I have not seen any reason why it should be done. 

Long story: 

I started quantifying syllable count in a slightly different way after some research. 

There are 2 methods to counting syllables from what I have seen: using dictionaries (where it is more reliable) or using some heuristic based method (which is what textstat uses). 

The dictionary method is accurate, but many words are not in the dictionary (at least for what I wanted). The heuristic method will always get some words wrong as there are problems with diphthongs (e.g. most methods will get either "usually" or "beautiful" wrong as 2+ vowels either count as a diphthong (one syllable) or not). So to cut down on this, I use a 2 step measure, where a first query a dictionary in NLTK and, if it is not in there, then use a heurstic measure like textstat. 

First you need to download a dictionary through nltk. Then import. 

```
import re
from nltk.corpus import cmudict
d = cmudict.dict()
```

The structure of the functions are like this: 

```
def count_syllables(wrd):
    #Make sure word contains a vowel before sending to dictionary
    restr=re.compile('[AEIOUYaeiouy]')
    if restr.search(wrd):
        try:
            cnt=count_syllables_primary(wrd)
        except:
            cnt=count_syllables_secondary(wrd)
        #If multiple syllable alternatives exist, return the largest.
        if type(cnt) is list:
            sylCount=max(cnt)
        else:
            sylCount=cnt
    else:
        sylCount = 0
return sylCount
```

So there are two functions primary and secondary. The primary one queries the dictionary. The second one queries the heuristic function. For the secondary one you  can use textstat one (but I'd remove the 0.1. I actually used a different one that I adapted from http://shallowsky.com this website.)

```
def count_syllables_primary(word):
  return [len(list(y for y in x if isdigit(y[-1]))) for x in d[word.lower()]]

def count_syllables_secondary(word):
    vowels = ['a', 'e', 'i', 'o', 'u']
    on_vowel = False
    syl = 0
    lastchar = None
    word = word.lower()
    try:
        for c in word:
            is_vowel = c in vowels
            if on_vowel == None:
                on_vowel = is_vowel
            # y is a special case
            if c == 'y':
                is_vowel = not on_vowel
            if is_vowel:
                if not on_vowel:
                    syl += 1
            on_vowel = is_vowel
            lastchar = c
        if word[-1] == 'y' and not on_vowel:
            syl += 1
    except:
        syl=0
return syl
```

From my experimenting around several months ago, this gave me the best results.

**Comment by creedrogers** [comment]
This looks great.  It might be nice to note in the documentation, or a code comment, that there is a dependency on the NLTK.  It's handled really well with the try/except block, but still.

I don't understand the check for is_digit in the primary method - could you explain that?

**Comment by wiheto** [comment]
Just to be clear I have nothing to do with this textstat package. I just thought that I'd provide the  solution I came up with since you were having the same problem. And I am sorry if I wasn't clear in what I wrote above that it needs NLTK. 

So after you have run the `d = cmudict.dict()`,iIf the word you look up is 'installer', you get the following back in the the cmudict.dict()

In [1]: d['installer']
Out[1]: [['IH0', 'N', 'S', 'T', 'AO1', 'L', 'ER0']]

I don't fully understand everything in the NLTK coding, but what I know is that all the new syllables have digits in them (and this is the case for all words). So you take the length of the words elements in the lsit with a digit in to get the syllable count. Sometimes words are coded in multiple ways:

```
In [2]: d['restaurant']
Out[2]: 
[['R', 'EH1', 'S', 'T', 'ER0', 'AA2', 'N', 'T'],
 ['R', 'EH1', 'S', 'T', 'R', 'AA2', 'N', 'T']]
```

That is the reason for the double loop. And in the functions above, I take the max whenever this occurs.

**Comment by creedrogers** [comment]
Right, I realize that you are not the repo owner.  I figure this conversation is for everyone's benefit, including that of the repo owner.  My apologies for not being clearer.

You, on the other hand, were very clear about the dependency of the Python NLTK in your comments.  I just meant that if the syllable count algorithm changes to your idea of primary/secondary methods, then I think the official docs for the package would need to include a note indicating such.  From what I can tell, you have the try/except block taking care of the instance where the code is used without the NLTK, which is great, but as I said, it's probably a wise idea to put that dependency in the docs.

And thank you for the explanations.

**Comment by wiheto** [comment]
Sorry for the misunderstanding (too hot where I am). 

So for completeness for anyone who wants it. Here is a slightly modified version of the functions that also excludes the try/except so people will see if they need NLTK.  

```
def count_syllables(wrd,d=cmudict.dict()):
    '''
    Count syllables works in two steps. First it searches a dictionary wherer the answer is usually better. If missing from the dictionary a heuristic is applied where the vowels are counted.
    Wrd: string of word 
    d = dictionary of words coming from NLTK 
    Requires: nltk and a dictionar. To get cmudict, install NLTK and run "from nltk.corpus import cmudict"
    '''
    #Make sure word contains a vowel before sending to dictionary
    restr=re.compile('[AEIOUYaeiouy]')
    if restr.search(wrd):
        cnt=count_syllables_primary(wrd,d)
        #If 0 from above function, go to secondary function
        if cnt==0:
            cnt=count_syllables_secondary(wrd)
        #If multiple syllable alternatives exist, return the largest.
        if type(cnt) is list:
            sylCount=max(cnt)
        else:
            sylCount=cnt
    else:
        sylCount = 0
    return sylCount

    
def count_syllables_primary(word,d):
    inList=any(word in x for x in d)
    if inList != 0:
        return [len(list(y for y in x if isdigit(y[-1]))) for x in d[word.lower()]]
    else:
        return 0

def count_syllables_secondary(word):
    # Adapted from Akkana Peck http://shallowsky.com.
    vowels = ['a', 'e', 'i', 'o', 'u']
    on_vowel = False
    syl = 0
    lastchar = None
    word = word.lower()
    try:
        for c in word:
            is_vowel = c in vowels
            if on_vowel == None:
                on_vowel = is_vowel
            # y is a special case
            if c == 'y':
                is_vowel = not on_vowel
            if is_vowel:
                if not on_vowel:
                    # We weren't on a vowel before.
                    # Seeing a new vowel bumps the syllable count.
                    syl += 1
            on_vowel = is_vowel
            lastchar = c
        if word[-1] == 'y' and not on_vowel:
            syl += 1
    except:
        syl=0
    return [syl]


```

**Comment by shivam5992** [comment]
This is updated in the latest code. Thanks
