### ISSUE TITLE
Spache Formula

### ISSUE THREAD

**Issue by DonaldTsang** [shivam5992/textstat#106]
See https://github.com/DaveChild/Text-Statistics

**Comment by alxwrd** [comment]
hi @DonaldTsang 

Thanks for raising this. This seems to already be implemented [here](https://github.com/shivam5992/textstat/blob/9c6eded93638217c6ffb2c3d52e0ea8c704b1e75/textstat/textstat.py#L402).

**Comment by DonaldTsang** [comment]
Please update the documentation if that is the case, thank you for your attention.
