### ISSUE TITLE
 'textstatistics' object has no attribute 'set_lang'

### ISSUE THREAD

**Issue by pratiksha-cobiro** [shivam5992/textstat#117]
I am using textstat==0.5.6 for flesch_reading_ease
I am using non English text and getting this error.

On downloading the zip I see that set_lang is not there in class textstatistics

When will there be new release which will have set_lang method

**Comment by alxwrd** [comment]
hi @pratiksha-cobiro 👋

Thank you for raising this.

I have just released versions 0.5.7 (Python2) and 0.6.0 (Python3) onto PyPi. These versions contain limited support for non-English text.
