### ISSUE TITLE
conda install -c mlgill textstat not working

### ISSUE THREAD

**Issue by Rexfarell** [shivam5992/textstat#118]
When trying to install textstat via conda I get an error: The package in not available from the current channels.

**Comment by alxwrd** [comment]
Hi Rexfarell 👋 

Thanks for raising this.

I'm not too familiar with Anaconda, could you provide the full output of the command `conda install -c mlgill textstat`?

It would also be worth noting that the version of textstat at [https://anaconda.org/mlgill/textstat](mlgill/textstat) is `v0.3.1`, which at this point is three years old, and seems to be managed by a third party.

**Comment by Rexfarell** [comment]
thank you for your reply,

I screen captured the output:

[image: image.png]

**Comment by alxwrd** [comment]
hi @Rexfarell, the email hasn't posted the image to github correctly.

**Comment by alxwrd** [comment]
Note to myself: Should we also release to Anaconda officially?

**Comment by Rexfarell** [comment]
Here it goes, hopefully you'll be able to see it this time.

ps:You are not asking me, but not releasing for Anaconda seems really
strange.

**Comment by alxwrd** [comment]
Sorry, it still isn't posting. Might be best to log onto Github and add an image through the site.

**Comment by alxwrd** [comment]
I've created #119 to investigate the possibility of a conda release at some point.

**Comment by Rexfarell** [comment]
![image](https://user-images.githubusercontent.com/42093317/71790121-10886280-3072-11ea-8da4-04c1fa98044c.png)

**Comment by Rexfarell** [comment]
![image](https://user-images.githubusercontent.com/42093317/71790335-3bbf8180-3073-11ea-90ba-4938eff4eca0.png)

**Comment by alxwrd** [comment]
hi @Rexfarell it appears that the current conda release for textstat is only available for Linux and macOS. You can see at the distribution channel for that user for Windows is almost empty compared to the distribution channel for Linux.

https://conda.anaconda.org/mlgill/win-64
https://conda.anaconda.org/mlgill/linux-64

I've raised #119 to look into officially releasing to conda in the future. For now, it might be quicker and easier to install from PyPi if you can: https://pypi.org/project/textstat/

**Comment by alxwrd** [comment]
hi @Rexfarell, @mwilson8 has done the work conda-forge/staged-recipes#10785 here to get textstat into conda forge.

https://anaconda.org/conda-forge/textstat
