### ISSUE TITLE
Conda release

### ISSUE THREAD

**Issue by alxwrd** [shivam5992/textstat#119]
Will require conda to be installed, the minimal installer can be found here: https://docs.conda.io/en/latest/miniconda.html. After installation, turn off auto base with `conda config --set auto_activate_base false`.

Tutorial for building packages here: https://docs.conda.io/projects/conda-build/en/latest/user-guide/tutorials/build-pkgs.html

**Comment by mwilson8** [comment]
Just opened https://github.com/conda-forge/staged-recipes/pull/10785 for a conda release through the conda-forge channel. @alxwrd would you consider being a maintainer on that package?

**Comment by alxwrd** [comment]
@mwilson8 sure.

I'm not sure what that entails though, so if you could let me know what it looks like when textstat releases a new version?

**Comment by mwilson8** [comment]
> @mwilson8 sure.
> 
> I'm not sure what that entails though, so if you could let me know what it looks like when textstat releases a new version?

Basically every time a new version is released, conda forge has a bot that will push an update to the feedstock; a maintainer merges that after the checks have passed, or makes necessary changes if some checks fail

**Comment by alxwrd** [comment]
hi @mwilson8, I see conda-forge/staged-recipes#10785 has been merged. Should I close this issue?

**Comment by mwilson8** [comment]
> hi @mwilson8, I see [conda-forge/staged-recipes#10785](https://github.com/conda-forge/staged-recipes/pull/10785) has been merged. Should I close this issue?

Yes; the merge into conda-forge was a no-arch platform, should fix any conda release issue

**Comment by alxwrd** [comment]
excellent, thank you 🎉
