### ISSUE TITLE
Outdated README.md

### ISSUE THREAD

**Issue by GuillemGSubies** [shivam5992/textstat#121]
There are some new functions added on 0.5.7 that are not in the README.md so the user has to read the code in order to know that they exist. The ideal would be having them all in the README with the others

**Comment by lclarko** [comment]
I can take this. Reading through the code leads me to believe that the functions should be grouped under separate headings, one for Averages & Aggregations, and another for scoring functions (reading ease, grade, indexes, etc.). There's also several difficult/easy word identifiers, which could be grouped together. Thoughts?
