### ISSUE TITLE
Flesch-Kincaid Grade Level

### ISSUE THREAD

**Issue by BradleyMerrillT** [shivam5992/textstat#124]
The documentation explains that the code "Returns the Flesch-Kincaid Grade of the given text. This is a grade formula in that a score of 9.3 means that a ninth grader would be able to read the document."  But when I run the code on text I have, the scores are all in the 90s.  Indeed, the results are very similar to the Flesch Reading Ease Score.  Am I doing something wrong, or is there an error in the code that it is not producing the grade level.

**Comment by alxwrd** [comment]
hi @BradleyMerrillT, thanks for raising this 🎉 

Could you have a look at #91 and #77? It seems like you might have a similar issue.

Currently, textstat expects text to be "cleaned" and well-formatted to provide a proper result.

**Comment by BradleyMerrillT** [comment]
Thanks @alxwrd .  Article 77 seems helpful.  I am reading product reviews, and the punctuation is terrible.
