### ISSUE TITLE
Amend the pypi.org docs

### ISSUE THREAD

**Issue by giampaolo44** [shivam5992/textstat#125]
Sorry to post it here. I checked if I could amend directly the docs at pypi but did not find the way. Am available to do it myself if you point me in the right direction.

In the [pypy docs](https://pypi.org/project/textstat/) it (still?) signals to use `textstat.set_language(lang)` instead that the correct `textstat.set_lang(lang)`. 

In addition or as substitute to changing the docs maybe placing an alias with `textstat.set_language` pointing to `textstat.set_lang(lang)` would work as well?

Hope this helps

**Comment by alxwrd** [comment]
hi @giampaolo44, thank you for raising this! 🎉 

I've pushed version [0.6.1](https://pypi.org/project/textstat/0.6.1/) to PyPI which will resolve this.
