### ISSUE TITLE
Sentence count fails when there are more than one new line characters between sentences 

### ISSUE THREAD

**Issue by AndrewMartchenko** [shivam5992/textstat#134]
When two sentences are separated by a full stop and more than one new line characters, the sentence count function detects this as one sentence.
For example, the following will return a count of 1:
`count = textstat.sentence_count('Sentence one.\n\nSentence two.')`

Edit:
Any two white spaces cannot be used after a full stop to separate sentences.

**Comment by alxwrd** [comment]
Hi @AndrewMartchenko! Thank you for raising this.

Currently, textstat expects well-formatted text as input.

There is some work to be done here. We currently have #77 open that is mainly about _no_ spaces between sentences but I guess this applies as well.

The culprit for this instance is [here](https://github.com/shivam5992/textstat/blob/master/textstat/textstat.py#L162).

I suspect count _one or more_ spaces could work here, but it would need some testing.
```diff
--        sentences = re.split(r' *[\.\?!][\'"\)\]]*[ |\n](?=[A-Z])', text)
++        sentences = re.split(r' *[\.\?!][\'"\)\]]*[ |\n]+(?=[A-Z])', text)
```

**Comment by AndrewMartchenko** [comment]
Hi @alxwrd, Thank you for the quick response.

I find the following a bit more forgiving:
` sentences = re.split(r' *[.\?!][\'"\)\]]*\s+(?=[A-za-z\d])', text)`

It allows for any white space between sentences and it also allows for sentences to begin with lower case characters and numerals.

Perhaps it may be useful make these features optional by adding flags to `sentence_count`.

**Comment by alxwrd** [comment]
I'm closing this issue in favour of #77.
