### ISSUE TITLE
Can we use this algorithm on other language. 

### ISSUE THREAD

**Issue by ykkhan** [shivam5992/textstat#136]
As our work is based on the Urdu language. Can we apply this algorithm (Flesch reading, gunning fog etc) to the Urdu language?

**Comment by alxwrd** [comment]
Hi @ykkhan, unfortunately the research behind most of the indexes were based on the English language. I don't know how well, if at all, they would work in other languages.

There's current #94 open to track language support for textstat.

If you know of any research for algorithms for Urdu, please feel free to respond here or open a new issue with a link to the paper.
