### ISSUE TITLE
Update documentation with maximum Value of text_standard()

### ISSUE THREAD

**Issue by nikchha** [shivam5992/textstat#137]
Hi,

I would like to use the text_standard() method to calculate readability for a large document base. I would like to reverse-code the index so that larger values indicate better readability. The simplest way I could come up with is to use the maximum value of the function and subtract each method result.

Would it be possible to add the maximum value of text_standard() (and perhaps the other indices) to the documentation? 

Thank you!

**Comment by alxwrd** [comment]
Hi @nikchha, thank you taking the time to raise an issue.

I'm not sure what you're requesting is practically possible. The output for
the formulas will increase with difficultly because any given text could
always be made more 'difficult', but the lowest scoring text could never be
made 'easier'.

"The cat sat on the mat"

"The feline perched in the center of the floor covering"

The first example cannot be made simpler, but both examples could be made
more complex.

**Comment by nikchha** [comment]
Hi @alxwrd 

Thank you very much for your quick reply. 
I was just under the impression that there must be an upper bound for difficulty values. 
However, if this is not the case I am sorry for raising the question.

Best,
Niklas

**Comment by alxwrd** [comment]
I think you're right that there probably is an upper bound for text difficulty. A certain piece of purposefully complex text might not be of any use to anyone, but I don't think textstat can make the determination of the ceiling.

If you want to reverse the result of `.text_standard`, the best thing might be for you to choose your own cut off point.

```python
>>> textstat.text_standard(text, float_output=True)
10.0
>>> textstat.text_standard(text)
'9th and 10th grade'
```

```python
>>> # http://www.stephenhicks.org/2009/06/28/philosophys-longest-sentences-part-3/
>>> aristotle = "Now if the function of man is an activity of ... with the best and most complete."
>>> textstat.text_standard(aristotle, float_output=True)
73.0
>>> textstat.text_standard(aristotle)
'72nd and 73rd grade'
```

If your cut off is the 15th grade (college/university), then Aristotle will just be classed as 15th grade.

**Comment by alxwrd** [comment]
I'm going to close this issue because I don't think there's anything for textstat to implement/change.

I'm not closing the conversation though. If there's more you want to add or discuss, please feel free to do so 🙂
