### ISSUE TITLE
The sentence count regex only checks Latin characters

### ISSUE THREAD

**Issue by AjBreidenbach** [shivam5992/textstat#139]
This means Russian is not supported for flesch_reading_ease because the average sentence length is calculated incorrectly.

**Comment by alxwrd** [comment]
Hi @AjBreidenbach, thank you for raising this. You're right, the look ahead `?=[A-Z]` should probably be `?=[w]`, or similar.

Do you have an example where this isn't working as expected for a failing test case? If you could add it here, or raise a pull request with a failing test, that would be great.

**Comment by AjBreidenbach** [comment]
Just taking a look at a regex inspector, I guess there would need to be a case-sensitive version of ?=[\w] 

Would it be worth considering having the sentence count regex be a property that could be set on the texstat object, similar to `set_lang`?  My own use cases involve processing some messier texts.

**Comment by AjBreidenbach** [comment]
I made another fork to get on with my project.  This is what I did to get it implemented https://github.com/AjBreidenbach/bvtextstat/commit/daab1d2242e3f37a20c0b6a08e9ed7eaf2429d6b
It sets the regex for Russian when set_lang is used to switch to Russian.
It just breaks the readability test, because the regex I used ignores Latin characters

**Comment by alxwrd** [comment]
@AjBreidenbach, sure. I'll drop the diff below for reference later.

I'm meaning to do some work around language support, but I'm not 100% on the best implementation so it's been on the back burner for a long time. More use cases like this help though!

```diff
diff --git a/textstat/textstat.py b/textstat/textstat.py
index 94f8076..71230f1 100644
--- a/textstat/textstat.py
+++ b/textstat/textstat.py
@@ -54,6 +54,11 @@
     },
 }
 
+sentence_regexes = {
+    "en": re.compile(r' *[\.\?!][\'"\)\]]*[ |\n](?=[A-Z])'),
+    "ru": re.compile(r' *[\.\?!][\'"»«\)\]]*[ |\n](?=[А-Я])')
+}
+
 
 def legacy_round(number, points=0):
     p = 10 ** points
@@ -90,6 +95,7 @@ def _cache_clear(self):
 
     def set_lang(self, lang):
         self.__lang = lang
+        self.__sentence_regex = sentence_regexes.get(self.__get_lang_root()) or sentence_regexes["en"]
         self.pyphen = Pyphen(lang=self.__lang)
         self._cache_clear()
 
@@ -163,7 +169,7 @@ def sentence_count(self, text):
         Sentence count of a text
         """
         ignore_count = 0
-        sentences = re.split(r' *[\.\?!][\'"\)\]]*[ |\n](?=[A-Z])', text)
+        sentences = self.__sentence_regex.split(text)
         for sentence in sentences:
             if self.lexicon_count(sentence) <= 2:
                 ignore_count += 1
```
