### ISSUE TITLE
Zero division error with new spanish formulas

### ISSUE THREAD

**Issue by GuillemGSubies** [shivam5992/textstat#140]
If I use:

```python
>>> textstat.szigriszt_pazos("")
>>> textstat.gutierrez_polini("")
>>> textstat.crawford("")
```

It will all raise an error because `total_words` is `0`. I can make a PR to solve it. 

I think that the ideal solution would be catching the error, raising a warning and returning a `0`. Letting the division error raise, can be problematic.

**Comment by alxwrd** [comment]
@GuillemGSubies thank you for raising this. Yes, I think you are right. There are other examples where `ZeroDivision` errors can occur, and in those cases we return `0`. If you can raise a PR to address this that would be great!

**Comment by GuillemGSubies** [comment]
Here it is #144
