### ISSUE TITLE
Exception handling

### ISSUE THREAD

**Issue by skyjur** [shivam5992/textstat#15]
Hello, first of all great work, and thanks for sharing your library!

I want to comment on some of the things that are related to error handling in you code. There are a couple of small issues.

1)  At very least it is important to provide `Exception` class to the `except`

```
try:
    ...
except Exception:
    ...
```

If you don't provide `except Exception`, any kind of exception will be handled, including such as `KeyboardInterrupt`. Check https://docs.python.org/3/library/exceptions.html#exception-hierarchy. If you make an error and spin up an infinite loop it might be difficult to kill it if you handle KeyboarInterrupt, and don't raise any error.

2) In most cases class passed to except should be as concrete as possible. For example in this case:

```
    def avg_letter_per_word(self, text):
        try:
            ALPW = float(float(self.char_count(text))/float(self.lexicon_count(text)))
            return round(ALPW, 2)
        except:
            print("Error(ALPW): Number of words are zero, cannot divide")
            return
```
a number of different things can go wrong inside `try ... except`. However In any case it just spits out `Number of words are zero`. This will make it very hard to debug issues. Much better would be:
```
try:
   ...
except ZeroDivisionError:
   ...
```

3) Instead of `print()` much better way to report errors is `raise Exception('... message ...)`, ideally with a custom exception class derived in your code.

**Comment by shivam5992** [comment]
Thanks, I have merged your commits and updated it.

**Comment by ajrader** [comment]
Nice library. 
 I've noticed the same thing as @skyjur. 
For example:
 ```
def avg_syllables_per_word(self, text):
        syllable = self.syllable_count(text)
        words = self.lexicon_count(text)
        try:
            ASPW = float(syllable)/float(words)
            return round(ASPW, 1)
        except:
            print("Error(ASyPW): Number of words are zero, cannot divide")
            return
```
is an overlybroad exception and should be treated with a bit more care. Let me know if you want some more specific help on these items.
