### ISSUE TITLE
`textstat.syllable_count(text)` doesn't split by newlines

### ISSUE THREAD

**Issue by LKirst** [shivam5992/textstat#158]
`textstat.syllable_count(text)` uses [`text.split(' ')`](https://github.com/shivam5992/textstat/blob/b492e7e71fe3e5ce54feafc7dc0de0975f664970/textstat/textstat.py#L156) to split words and therefore doesn't split words separated by a newline character. This shouldn't make a large difference, because the pyphen syllable count is often incorrect anyway, but it still introduces noise.

**Comment by LKirst** [comment]
If I'm not mistaken, [`textstat.letter_count(text, ignore_spaces=True)`](https://github.com/shivam5992/textstat/blob/b492e7e71fe3e5ce54feafc7dc0de0975f664970/textstat/textstat.py#L115) also doesn't replace newline characters.

**Comment by alxwrd** [comment]
Hi @LKirst, thank you for this.

I agree, especially as [`lexicon_count`](https://github.com/shivam5992/textstat/blob/c0e048db5cb1b612567116cab2b70f33a6a7f17c/textstat/textstat.py#L129) _does_ remove newlines using `split()`.

**Comment by alxwrd** [comment]
- Update `syllable_count` to use `split()` and not `split(' ')`.
- Update `char_count` to ignore all white space as indicated by the doc string.
- Update `letter_count` to ignore all white space as indicated by the doc string.
