### ISSUE TITLE
Flesch Reading Ease Function not working

### ISSUE THREAD

**Issue by Senjuti** [shivam5992/textstat#16]
Here is my sample program:
import textstat

text = "The cat sat on the mat." 
print textstat.flesch_reading_ease(text)

Here is the output:
AttributeError: 'module' object has no attribute 'flesch_reading_ease'

I attempted to use "flesch_reading_ease(text)" but it resulted in the output: "NameError: name ''flesch_reading_ease' is not defined"

None of the other readability functions seem to work either. Am I doing something wrong?

**Comment by shivam5992** [comment]
use ->

from textstat.textstat import textstat 

instead of 

import textstat

**Comment by 4rshdeep** [comment]
update readme

**Comment by alxwrd** [comment]
hi @4rshdeep!

Sorry for any confusion, we made a change recently that means you can just do `import textstat`.

This change is not on pypi yet though.
