### ISSUE TITLE
Rounding of all outputs

### ISSUE THREAD

**Issue by LKirst** [shivam5992/textstat#162]
Why does textstat round all numeric outputs? The user could always round the result, but they can not "unround" it.

**Comment by alxwrd** [comment]
At this point, for backwards compatabilty. Textstat has pretty much _always_ rounded its outputs. [See this commit from 2014 - e874303dc](https://github.com/shivam5992/textstat/commit/e874303dc1175f4c5fbfdaaf18a4f4466fa9c256#diff-a2499e1f7f1c9a7c78e1dfb34cc55ce956cf0552119ee158228f6451ce1cc204R51).

I'm not against removing the rounding, but not until a major version release.
