### ISSUE TITLE
textstat.remove_punctuation(text) removes the dash in hyphenated words

### ISSUE THREAD

**Issue by LKirst** [shivam5992/textstat#169]
[`textstat.remove_punctuation(text)`](https://github.com/shivam5992/textstat/blob/c83d12353b120cdc1f43a446a797346de8d2ce00/textstat/textstat.py#L153) removes the dash in hyphenated words. The result is, that "Mexican-American" is returned as "mexicanamerican" and is counted as a 6 syllable word by `pyphen`, for all readability measures that depend on the syllable count.

It would probably make more sense to replace a dash between to letters with a space, instead of removing it.

**Comment by alxwrd** [comment]
Hi @LKirst, thank you for raising this, but I'm not so sure about this one.

I think there's a couple of conflicting things here.

First, I think the method `remove_punctuation` should remove all punctuation, regardless of contractions or hyphenated words.

Second, I understand the sentiment behind the change for hyphenated words. I think the issue for `remove_punctuation` seems to be that it's used for generating a word list in the following methods: `lexicon_count`, `syllable_count`, `long_word_count`, `monosyllabcount`. I think the problem with the word list issue is that in some cases (Mexican-American) it makes sense. In others, however, it might not: "mother-in-law", for example, I would argue is one word, 4 syllables - not 3 words of 2, 1, 1 syllables.

For a word list that doesn't strip apostrophes from contractions, I am looking at [addressing that soon](https://github.com/textstat/textstat-core/blob/main/textstat_core/word_collection.py#L30).

From stack exchange:
- [What counts as one word and what is two words](https://ell.stackexchange.com/questions/36557/what-counts-as-one-word-and-what-is-two-words)
- [“High-pitched”: one word or two words?](https://ell.stackexchange.com/questions/166610/high-pitched-one-word-or-two-words)

**Comment by LKirst** [comment]
I agree that the definition of what is a word is not trivial. I've removed the replacement of hyphens from the pull request. 
Could you accept the pull request until your solution of keeping apostrophes replaces it?
