### ISSUE TITLE
trouble with difficult_words()

### ISSUE THREAD

**Issue by mackie-m** [shivam5992/textstat#18]
The `difficult_words()` function seems not to be working properly.

In the top of `textstat.py` a txt-file is saved as a set in the variable `easy_word_set` like this:
`easy_word_set = set([ln.strip() for ln in pkg_resources.resource_stream('textstat', 'easy_words.txt')])`

The function code of `difficult_words()` is:
```
def difficult_words(self, text):
    text_list = text.split()
    diff_words_set = set()
    for value in text_list:
        if value not in easy_word_set:
            if self.syllable_count(value) > 1:
                if value not in diff_words_set:
                    diff_words_set.add(value)
    return len(diff_words_set)
```

If i understand it right (it's late and I'm a beginner), `if value not in easy_word_set:` checks whether `value` is in `easy_word_set`. If it is in `easy_word_set` , `diff_words_set` is not extended. 

However, when I call `ts.textstat.difficult_words("happy")`, the output is `1`, but "happy" is definitely in easy_words.txt, so output should be `0`.

What am I doing wrong?

**Comment by alxwrd** [comment]
@mackie-m I've been investigating this issue, and the issue seems to be releated to Python 3.

In Python 3: `pkg_resources.resource_stream('textstat', 'easy_words.txt')` results in the `bytes` type (`b"happy"`).

```python
>>>for word in pkg_resources.resource_stream('textstat', 'easy_words.txt'):
...    print(word)
b"happy" #etc.

>>>"happy" == b"happy"
False
```
I am about to raise a pull request for this.
