### ISSUE TITLE
New Version ?

### ISSUE THREAD

**Issue by Uettwillera** [shivam5992/textstat#184]
Hello, 

Thanks a lot for the package! Super useful

I was wondering when the new version will come out.

At the moment, the github package is not the same as the one you would find on https://pypi.org/project/textstat/#files

For the sentence_count function, on github, you have:
`sentences = re.findall(r'\b[^.!?]+[.!?]*', text, re.UNICODE)`

On pypi, sentences is defined as 
`sentences = re.split(r' *[\.\?!][\'"\)\]]*[ |\n](?=[A-Z])', text)`

Having tested it quite a bit myself, I would say the first is definitely the right one (for example when you have double spaces in a given text).

**Comment by alxwrd** [comment]
Released 0.7.3:
- https://github.com/shivam5992/textstat/releases/tag/0.7.3 
- https://pypi.org/project/textstat/0.7.3/

**Comment by Uettwillera** [comment]
Thanks a lot!

> Released 0.7.3:
> 
> * https://github.com/shivam5992/textstat/releases/tag/0.7.3
> * https://pypi.org/project/textstat/0.7.3/
