### ISSUE TITLE
How can I compute LIX by using functions currently provided by textstat?

### ISSUE THREAD

**Issue by YuanruiZJU** [shivam5992/textstat#19]
Recently, I am doing a research on readability of some text files. Thanks for your package to help me compute characteristics of readability of the text files. But one feature called "LIX" is not found from current version of textstat. 

Although there are other packages that can help me compute this feature, I am a little confused about the accuracy when using different packages to compute the readability characteristics. Because I find that readability characteristic values computed by a package named "readability" are a little different from values computed by textstat.

Could you tell me how to compute the feature "LIX" simply from current functions provided by textstat or add this function to the library?

Thanks

**Comment by shivam5992** [comment]
Hi YuanruiZJU, Thanks for the suggestion of adding LIX in current version, I will add it shortly. 
Thanks

**Comment by shivam5992** [comment]
Hi, Now you can compute lix using the function  "lix" .

**Comment by YuanruiZJU** [comment]
Thank you for your tool. :）
