### ISSUE TITLE
Performance issue when computing many readability features

### ISSUE THREAD

**Issue by YuanruiZJU** [shivam5992/textstat#20]
Thanks for your support and your tool can really help me do my research. But I also find performance problem when I compare your tool with another tool that compute readability characteristics of text named **readability**, especially when I must compute many readability features for the same text.

The python package **readability** requires user  first call its function `analyze_text`. After doing this step,
all base measurements that consume much time when they are computed such as number of words, number of sentences can be computed and temporarily stored.  By doing this, performance can be improved when someone want to compute many readability features at the same time.

But when I use **textstat** to compute readability features, some base features will be repeatedly computed. It is because needed base measurements are repeatedly computed in each function of **textstat**.

Hoping for your support!

Have a great week :)

Regards
Yuanrui

**Comment by shivam5992** [comment]
Thanks for your inputs, I will look at this.

**Comment by jnothman** [comment]
@YuanruiZJU You may wish to try [textacy's implementation](http://textacy.readthedocs.io/en/latest/api_reference.html#textacy.text_stats.TextStats)

**Comment by YuanruiZJU** [comment]
Thank you for your reply. That is exactly what I need.
