### ISSUE TITLE
Hyphenation improvement

### ISSUE THREAD

**Issue by haarburger** [shivam5992/textstat#21]
Hyphenation as implemented in `textstat` works okay but not very well. Is there a particular reason for not using a dictionary-based hyphenation?
 [Pyphen](http://pyphen.org) for example is based on LibreOffice dictionaries and written in pure Python.

If you'd also see this as an improvement, I can make a pull request.

**Comment by shivam5992** [comment]
Yes. this will be a good improvement. Please make a pull request. Thanks
