### ISSUE TITLE
function syllable_count returns a float value

### ISSUE THREAD

**Issue by YanTianqi** [shivam5992/textstat#24]
I find that syllable_count function returns non-integer result, and is always a multiple of 0.9
e.g. syllable_count('Hello') -> 1.8
e.g. syllable_count('how') -> 0.9
e.g. syllable_count('are') -> 0.9
e.g. syllable_count('you') -> 0.9
what does 0.9 syllable mean? shouldn't it be just 1 syllable

moreover, the syllable_count does not seem to follow the rule of summation, by calculating each word's syllable count, I expect the total syllable count of 'hello how are you' to be 1.8 + 0.9 + 0.9 + 0.9 = 4.5
but syllable_count('hello how are you') -> 5.4

Is this a common problem? Attached the screenshot as proof of the issue.
![capture](https://user-images.githubusercontent.com/7760158/30574362-0254b2ee-9d2c-11e7-82b1-fbd9a7306dc8.PNG)

**Comment by shivam5992** [comment]
This is updated. Thanks
