### ISSUE TITLE
compatibility issue and dictionary comprehension usage

### ISSUE THREAD

**Issue by codycollier** [shivam5992/textstat#3]
Thanks for making this library available and for your time.

There's a minor compatibility issue with python 2.5 and 2.6 here:
https://github.com/shivam5992/textstat/blob/master/textstat/textstat.py#L222

That line uses a dictionary comprehension, which wasn't introduced until later python versions (2.7?).  It should be a simple change:  

old:
d = {x: grade.count(x) for x in grade}

new:
d = dict([(x, grade.count(x)) for x in grade])

**Comment by shivam5992** [comment]
Thanks for pointing this. 
I have updated this in master branch
