### ISSUE TITLE
different results between similar packages

### ISSUE THREAD

**Issue by LeoPetrini** [shivam5992/textstat#30]
Hi!

I've noticed that the results between textstat and the following package https://github.com/mmautner/readability

differ quite a bit! Any idea?
Thanks!

**Comment by alxwrd** [comment]
From a first look: one thing that is different that will change the results between the packages is the syllable count.

```python
>>> import readability
>>> from textstat.textstat import textstat
>>> text = "The quick brown fox"
>>> readability_ = readability.Readability(text)

>>> textstat.syllable_count(text)
4
>>> readability_.analyzedVars["syllable_cnt"]
3.0
```

**Comment by aetherwu** [comment]
@alxwrd I had quick glance mmautner/readability. At least there are differences on tokenization process. I also found something like u'\n\n' in its tokenized words.

**Comment by alxwrd** [comment]
Good shout.

@shivam5992 Maybe this issue could be closed? There are differences between [readability](https://github.com/mmautner/readability) and textstat, but nothing that textstat is doing wrong.
