### ISSUE TITLE
Negative value of flesch_reading_ease score

### ISSUE THREAD

**Issue by AiliAili** [shivam5992/textstat#34]
Hi, 
When I use this package, I found the flesch_reading_ease score can return negative values, which does not make sense. And in the document, you also stated that it should be between 0 and 100. 

The text I am dealing with is as follows.

{{Infobox settlement 
|official_name =Kolibite
|native_name=
|settlement_type=Village
|image_skyline = 
|image_flag = 
|image_seal = 
|image_map = 
|mapsize = 
|map_caption = 
|pushpin_map =
|pushpin_map_size=
|pushpin_label_position =Location in Bulgaria
|subdivision_type = [[Countries of the world|Country]] 
|subdivision_name = {{f{{la}}g|Bulgaria}}
|subdivision_type1 =[[Provinces of Bulgaria|Province]]
|subdivision_name1 =[[Blagoevgrad Province]]
|subdivision_type2 =[[Municipalities of Bulgaria|Municipality]]
|subdivision_name2 =[[Strumyani]]
|leader_title = 
|leader_name = 
|area_total_km2      =
|population_as_of = 2007
|population_note = 
|population_total =
|population_footnotes   =
|population_metro = 
|population_density = 
|timezone =[[Eastern European Time|EET]]
|utc_offset = +2
|timezone_DST =  [[Eastern European Summer Time|EEST]]
|utc_offset_DST = +3
|latd=|latm=|lats=|latNS=N
|longd=|longm=|longs=|longEW=E
|elevation_m=
|website = 
|footnotes = 
}}
'''Kolibite''' is a village in the municipality of [[Strumyani]], in [[Blagoevgrad Province]], in southwestern [[Bulgaria]].<ref>[http://www.guide-bulgaria.com/SW/Blagoevgrad/Strumyani Guide Bulgaria], Accessed May 5, 2010</ref> 

==References==
{{reflist}}

{{Strumyani}}

{{coord|41|35|N|23|02|E|display=title|region:BG_type:city_source:GNS-enwiki}}

[[Category:Villages in Blagoevgrad Province]]

{{Blagoevgrad-geo-stub}}

**Comment by shivam5992** [comment]
Have you installed the latest version of textstat ? 
from where have you installed it - Github or PyPi?

**Comment by AiliAili** [comment]
Thank you for your timely reply.

Yes, I installed the latest version, from github through pip install  textstat

**Comment by alxwrd** [comment]
hi @AiliAili 👋 

The Flesch Reading Score resulting in a negative score is perfectly valid, and the highest score is 121.22.

> The highest (easiest) readability score possible is 121.22, (i.e. every sentence consisting of only one one-syllable words).

> While Amazon calculates the text of Moby Dick as 57.9, one particularly long sentence about sharks in chapter 64 has a readability score of −146.77.

Source: [Wikipedia](https://en.wikipedia.org/wiki/Flesch%E2%80%93Kincaid_readability_tests#Flesch_reading_ease)

I will make a PR to add a note about this in the README.

### Higher score

```python
from textstat.textstat import textstat

textstat.flesch_reading_ease("cat")
# Results in 121.22
```

### Lower score

```python
from textstat.textstat import textstat

textstat.flesch_reading_ease("""
Though amid all the smoking horror and diabolism of a sea-fight, sharks will
be seen longingly gazing up to the ship’s decks, like hungry dogs round a table
where red meat is being carved, ready to bolt down every killed man that is
tossed to them; and though, while the valiant butchers over the deck-table are
thus cannibally carving each other’s live meat with carving-knives all gilded and
tasselled, the sharks, also, with their jewel-hilted mouths, are quarrelsomely
carving away under the table at the dead meat; and though, were you to turn
the whole affair upside down, it would still be pretty much the same thing, that
is to say, a shocking sharkish business enough for all parties; and though
sharks also are the invariable outriders of all slave ships crossing the Atlantic,
systematically trotting alongside, to be handy in case a parcel is to be carried
anywhere, or a dead slave to be decently buried; and though one or two other
like instances might be set down, touching the set terms, places, and occasions,
when sharks do most socially congregate, and most hilariously feast; yet is
there no conceivable time or occasion when you will find them in such countless
numbers, and in gayer or more jovial spirits, than around a dead sperm whale,
moored by night to a whaleship at sea.""")
# Results in -138.97
```
