### ISSUE TITLE
Including RIX equations

### ISSUE THREAD

**Issue by DonaldTsang** [shivam5992/textstat#40]
Adding these two measurements would make textstat more feature-full.
LIX: https://github.com/mmautner/readability/blob/master/readability.py#L73
RIX: https://github.com/mmautner/readability/blob/master/readability.py#L83
Reference: https://github.com/mmautner/readability

**Comment by shivam5992** [comment]
Hi Donald, Thanks for sharing. 
LIX is already implemented. But sure we will add RIX.

**Comment by DonaldTsang** [comment]
Please edit the readme regarding LIX and RIX

**Comment by MKaras93** [comment]
Hello, first time contributor here. Can I work on implementing the RIX formula as stated in above comment?
