### ISSUE TITLE
Documented import does not work

### ISSUE THREAD

**Issue by tripleee** [shivam5992/textstat#43]
The current instructions in `README.md` say

    import textstat

However, this doesn't bring in the module.  I am presently forced to use

    from textstat.textstat import textstat

The final `textstat` is a package-global instance of the internal class `textstatistics` which is a slightly odd design.

A common solution is to encapsulate this in the package's `__init__.py`

**Comment by tripleee** [comment]
Oh, my bad, I had an old version from PyPi.

**Comment by FMCumhaill** [comment]
I have the issue, how did you force install latest from PyPi? @tripleee

**Comment by alxwrd** [comment]
Hi @FMCumhaill :wave:!

I think the previous comment means that @tripleee had an old version when compared to the state of the GitHub repo.  of textstat, which was obtained from pypi.

The README in the GitHub repository reflects the current development version. If you wish to install this, feel free by:

```shell
git clone https://github.com/shivam5992/textstat.git
cd textstat
pip install .
```

Hope this helps 🙂
