### ISSUE TITLE
Pip build not configured correctly?

### ISSUE THREAD

**Issue by mcnuttandrew** [shivam5992/textstat#46]
I'm having some trouble running the code as it is described in the documentation. I'm on python v3.6, and I've downloaded and installed textstat using pip (v10.0.1). When I run 

```python
import textstat
print(textstat.flesch_reading_ease("here is my example string maybe perhaps?"))
```

I get an error like

```sh
AttributeError: module 'textstat' has no attribute 'flesch_reading_ease'
```

I'm kinda new to python so I'd totally believe that I'm doing something wrong? But it looks like all of the methods are not correctly exported on the build that is currently available on pypi

**Comment by alxwrd** [comment]
Hi @mcnuttandrew :wave: !

The information in the README currently applies to the version in development here on GitHub.

The README at https://pypi.org/project/textstat/ shows how to use textstat using the version on pypi.

```
python
from textstat.textstat import textstat

print(textstat.flesch_reading_ease("here is my example string maybe perhaps?"))
```

If you want to use the current development version, you can see instructions in #43.

> ```shell
git clone https://github.com/shivam5992/textstat.git
cd textstat
pip install .
```

**Comment by mcnuttandrew** [comment]
Hey @alxwrd 

Thanks for the quick response! That solution works great for me. 

It would be really helpful if you could spell out that there are different usages in the main documentation. I'd be happy to file a PR if you like.

**Comment by alxwrd** [comment]
@mcnuttandrew I agree it's a bit confusing currently. The ideal fix here is a new release is made on PyPi.

@shivam5992 Could you push a new release? Or add me maintainer on PyPi? (same username https://pypi.org/user/alxwrd/)
