### ISSUE TITLE
file "textstat/easy_word_list" can't be found

### ISSUE THREAD

**Issue by Henry2012** [shivam5992/textstat#5]
I used os module to specify the path of the file. 

`
basepath = os.path.dirname(__file__)
os.path.join(basepath, 'easy_word_list')
`

**Comment by Haythamamin** [comment]
where did you add this line?

**Comment by shivam5992** [comment]
I will fix this today

On Friday 13 November 2015, Haytham Amin <notifications@github.com> wrote:

> where did you add this line?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/shivam5992/textstat/issues/5#issuecomment-156290923>.
>


-- 
Regards.
Shivam Bansal
+91-9810380015

**Comment by Haythamamin** [comment]
Thank you

**Comment by Haythamamin** [comment]
Also the first bug still occure if you pip install the package but it got resolved when installed the package locally. By locally I mean download source code, build and install.

**Comment by shivam5992** [comment]
I will do that too

On Friday 13 November 2015, Haytham Amin <notifications@github.com> wrote:

> Also the first bug still occure if you pip install the package but it got
> resolved when installed the package locally. By locally I mean download
> source code, build and install.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/shivam5992/textstat/issues/5#issuecomment-156310376>.
>


-- 
Regards.
Shivam Bansal
+91-9810380015
