### ISSUE TITLE
Lexicon count is incorrect

### ISSUE THREAD

**Issue by alxwrd** [shivam5992/textstat#50]
The `lexicon_count` of the `long_test` in the tests is currently incorrect. It is incorrectly counting the "..." as a word because there is a space either side.

The word count of the `long_test` should be 375, not 376.

**Comment by alxwrd** [comment]
Also, with `remove_punc=True` any '&' symbols are removed and not counted. I feel like they should be counted as it represents 'and', but it also seems weird to count them when you explicitly say to ignore punctuation.

@shivam5992, do you have any thoughts?

**Comment by MKaras93** [comment]
Should punctuation affect lexicon_count at all? Words should be words and I think it would be safer to count them after removing all punctuation, leaving only letters. It would also solve the "..." problem.

I'm not sure I understand the point of having removepunct argument in this function.

**Comment by alxwrd** [comment]
@MKaras93 agree. I wouldn't like to remove the `remove_punc`argument though for legacy reasons. I have a fix in mind for the "..." issue.

The main thing is "the cat and the dog" is 5 words. Is "the cat & the dog" still 5 words or 4?

**Comment by MKaras93** [comment]
After some research: It seems it's totally arbitrary, different algorithms do this in different ways. MS Word, which is the most popular tool if comes to counting words, counts everything between two spaces as a word - so even "...". However, from a library designed precisely for text statistics I would expect different options to choose from.
