### ISSUE TITLE
How to get the value of text_standard function?

### ISSUE THREAD

**Issue by rushdishams** [shivam5992/textstat#55]
Hello @shivam5992 , if I would like to get the actual value from `textstat.text_standard(text)` function, how do I do that? Right now the `float_output` variable is hard-coded to `None`.

**Comment by alxwrd** [comment]
hi @rushdishams!

To get the float output you would pass `True` as a keyword argument to the `text_standard` function.

```python
textstat.text_standard(text, float_output=True)
```

**Comment by rushdishams** [comment]
Hi @alxwrd , 

With the following code snippet-
`from textstat.textstat import textstat
text = 'Playing games has always been thought to be important to'
print(textstat.text_standard(text, float_output=True))`

I am getting an error:
`TypeError: text_standard() got an unexpected keyword argument 'float_output'
PS C:\pyworkspace\dummy> & C:/Anaconda3/python.exe c:/pyworkspace/dummy/simple_test.py
Traceback (most recent call last):
  File "c:/pyworkspace/dummy/simple_test.py", line 3, in <module>
    print(textstat.text_standard(text, float_output=True))
  File "C:\Anaconda3\lib\site-packages\repoze\lru\__init__.py", line 348, in cached_wrapper
    val = func(*args, **kwargs)
TypeError: text_standard() got an unexpected keyword argument 'float_output'`

**Comment by alxwrd** [comment]
@rushdishams  Apologies, I thought the `float_output` was in the latest version on PyPi but it appears it isn't! 😅 

You can install the latest version of textstat directly from GitHub using `pip`:

```shell
pip install git+https://github.com/shivam5992/textstat
```

I am planning on doing a proper release to PyPi soon. (#46)

**Comment by alxwrd** [comment]
@rushdishams  no you're right that looks incorrect. I would expect `float_output` to return a `float`, and at the very least an `int`, but not a `str`. I will look at getting that fixed.

**Comment by rushdishams** [comment]
Thanks @alxwrd , waiting to get the update from you. :)
