### ISSUE TITLE
Error importing textstat

### ISSUE THREAD

**Issue by jhpyle** [shivam5992/textstat#60]
Before, the `__init__.py` file was empty.  Now it contains `from textstat.textstat import textstat`.

I get the following:
```
Python 2.7.14+ (default, Dec  5 2017, 15:17:02) 
[GCC 7.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import textstat
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/share/docassemble/local/local/lib/python2.7/site-packages/textstat/__init__.py", line 1, in <module>
    from textstat.textstat import textstat
ImportError: No module named textstat
```

**Comment by alxwrd** [comment]
hi @jhpyle !

Thank you for reporting this! 🎉 

I've just pushed an update to PyPi that should make the importing compatible with Python 2 and 3. Could you update your version of `textstat` and try again?

**Comment by alxwrd** [comment]
@jhpyle I'm closing this for now, if you're still having issues feel free to re-open this issue :)

**Comment by jhpyle** [comment]
Sorry, I keep forgetting to follow up.  It works for me in the new version.  Thanks!
