### ISSUE TITLE
Avg letter per Word is Wrong

### ISSUE THREAD

**Issue by RAZelzner** [shivam5992/textstat#67]
Hey there,

i think there is a counting problem with the Avg letter per Word.

Code 
`textstat.avg_letter_per_word("﻿thisissued percent .")`

So the result is: 
> 9.5

I expected:
> 8.5

There are 17 letters and two words. So 17/2 = 8,5.
I think avg_letter... count the **first** spaces and punctuation as letters.

I tried it with the Text `"﻿thisissued          percent                ."` (Here are 10 Spaces between each word, but i cant show it inhere)
and also get the result 
> 9.5

Thanks for help.

Richard

**Comment by alxwrd** [comment]
hi @RAZelzner!

Your string starts with a []() BOM (byte order marker) character, which is giving you the odd result.

**Comment by alxwrd** [comment]
_Sorry for the close, fat fingers on mobile_

**Comment by alxwrd** [comment]
For reference: `avg_letter_per_word` uses a character count instead of a letter count. It might be worth creating 2 new methods `avg_character_per_word` and `letter_count`.

**Comment by RAZelzner** [comment]
Hey @alxwrd,
thanks for your fast and far-reaching reply and for making the bug clear.

I also think that this bug has an effect to the `coleman_liau_index`.  By myself i dont use the `coleman_liau_index` to measure the readability of documents.

**Comment by alxwrd** [comment]
@RAZelzner I've just pushed [0.5.4](https://github.com/shivam5992/textstat/releases/tag/0.5.4) to PyPi.
