### ISSUE TITLE
Python 3 Compatability

### ISSUE THREAD

**Issue by kashev** [shivam5992/textstat#7]
`textstat` is not Python 3 compatible. I think the biggest problem is that it has old style print statements for errors, when these should either be new style print functions, or even better, thrown exceptions.

**Comment by mjirv** [comment]
For personal purposes, I forked and made compatible with Python 3 using new print statements at https://github.com/shivam5992/textstat3.

**Comment by shivam5992** [comment]
Thanks. Its updated now.

**Comment by SGMcCalla** [comment]
I am not able to pip install or easy install textstat3:

>pip install textstat3
Collecting textstat3
  Could not find a version that satisfies the requirement textstat3 (from versions: )
No matching distribution found for textstat3

>easy_install textstat3
Searching for textstat3
Reading https://pypi.python.org/simple/textstat3/
Couldn't find index page for 'textstat3' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
No local packages or working download links found for textstat3
error: Could not find suitable distribution for Requirement.parse('textstat3')
