### ISSUE TITLE
Add the new Dale-Chall readability formula

### ISSUE THREAD

**Issue by alxwrd** [shivam5992/textstat#74]
Need to add the new Dale-Chall formula. Not sure what to call the method. Seems silly to call it `new_dale_chall_readability_score()`. 🤔 

Details here: http://www.readabilityformulas.com/new-dale-chall-readability-formula.php

---

Compute the following equation:
- Raw Score = 0.1579 * (PDW) + 0.0496 * ASL
- Raw Score = Reading Grade of a reader who can comprehend your text at 3rd grade or below.
- PDW = Percentage of Difficult Words
- ASL = Average Sentence Length in words
- If (PDW) is greater than 5%, then:
  - Adjusted Score = Raw Score + 3.6365,
- otherwise
   - Adjusted Score = Raw Score
- Adjusted Score = Reading Grade of a reader who can comprehend your text at 4th grade or above.
- Use the following table to get the Adjusted Grade Level:

| ADJUSTED SCORE | GRADE LEVEL                            |
|----------------|----------------------------------------|
| 4.9 and Below  | Grade 4 and Below                      |
| 5.0 to 5.9     | Grades 5 - 6                           |
| 6.0 to 6.9     | Grades 7 - 8                           |
| 7.0 to 7.9     | Grades 9 - 10                          |
| 8.0 to 8.9     | Grades 11 - 12                         |
| 9.0 to 9.9     | Grades 13 - 15 (College)               |
| 10 and Above   | Grades 16 and Above (College Graduate) |

**Comment by akarsh3007** [comment]
@alxwrd I will add a PR for this as well.

**Comment by akarsh3007** [comment]
@alxwrd  Here is the [PR](https://github.com/shivam5992/textstat/pull/90)
