### ISSUE TITLE
Reading time

### ISSUE THREAD

**Issue by alxwrd** [shivam5992/textstat#76]
It'd be nice to be able to calculate reading time. There are a lot of articles that put adults words per minute at 200-275.

https://marketingland.com/estimated-reading-times-increase-engagement-79830
https://blog.medium.com/read-time-and-you-bc2048ab620c
http://www.craigabbott.co.uk/how-to-calculate-reading-time-like-medium

There's the possibility to just have a `textstat.reading_time(words_per_minute=200)`, which is simple.

It'd be nice to have `reading_time` be based on the complexity of the text though!

There are a few of papers I found (I haven't read them yet) that might provide some insight.

> Ronald P. Carver (1976) Word Length, Prose Difficulty, and Reading Rate
https://journals.sagepub.com/doi/pdf/10.1080/10862967609547176

> Ronald P. Carver (1989) Silent Reading Rates in Grade Equivalents 
https://journals.sagepub.com/doi/pdf/10.1080/10862968909547667

> Keith Rayner, Elizabeth R. Schotter, Michael E. J. Masson, Mary C. Potter, and Rebecca Treiman (2016) So Much to Read, So Little Time: How Do We Read, and Can Speed Reading Help?
https://journals.sagepub.com/doi/pdf/10.1177/1529100615623267

**Comment by kishiyamat** [comment]
Calculating reading time sounds by counting words sounds good. This paper might provide some insight too!

> John Hale (2001) A Probabilistic Earley Parser as a Psycholinguistic Model
> https://www.aclweb.org/anthology/N01-1021

**Comment by alxwrd** [comment]
@kishiyamat excellent, thank you :tada:

**Comment by russelljjarvis** [comment]
I am interested in if these reading time metrics would be used to inform the text-stat `standard` reading score.

**Comment by alxwrd** [comment]
hi @russelljjarvis, I would expect it to be the other way around. A higher score would mean a longer reading time.

**Comment by akarsh3007** [comment]
@alxwrd do we have any plans on how are we going to implement this? I went through the links you posted, that seems straight forward. I will go over the paper's as well. Let me know if you have any plans in mind. I will start working on this after that.

**Comment by alxwrd** [comment]
@akarsh3007 apologies, I think your message slipped through in my notifications! Currently, I have no plans on how to tackle this. If you have some thoughts, feel free to work on this. You can always open a draft PR where we can discuss.

**Comment by akarsh3007** [comment]
@alxwrd Thanks for your reply, I will give this a thought and open a PR soon

**Comment by kishiyamat** [comment]
@alxwrdHere @akarsh3007 Here is my [PR](https://github.com/shivam5992/textstat/pull/102)
