### ISSUE TITLE
Flesch Reading Ease and Flesch Kincaid Grade Level scores 

### ISSUE THREAD

**Issue by Crista23** [shivam5992/textstat#78]
Hi, I am getting some contradictory scores when using the Flesch Reading Ease and Flesch Kincaid Grade Level metrics as implemented in textstat. As I need to calculate them at corpus level, I am passing the entire content of the text file to these functions. I am wondering if instead I should compute them at sentence level and then average for all sentences in the file? Can you please advise which is the way to go? Thanks!

**Comment by alxwrd** [comment]
Hi @crista23 :wave:

Thank you for reporting this. Do you have the ability to share the text you're trying to analyse? If not, a small example that causes the discrepancy would be great!

**Comment by alxwrd** [comment]
@Crista23 I'm going to close this issue for now as more information is needed.

Feel free to reopen this issue with an example ✨
