### ISSUE TITLE
how to cite? collaborators?

### ISSUE THREAD

**Issue by russelljjarvis** [shivam5992/textstat#79]
Hi, Sorry this may be the wrong place to post this message, but I created a kind of mashup technology that builds from your work:
https://github.com/russelljjarvis/ScienceAccessibility
I wonder if you know how I can meet people who would want to collaborate, and also how do I cite text-stat properly?

**Comment by alxwrd** [comment]
hi @russelljjarvis :wave:!

Thank you for sharing your project!

If it's research you're hoping to publish, I'm afraid I'm not in academia myself, so I wouldn't be able to help you find collaborators. As far as I'm aware, textstat is not currently citeable. For citations, you would need to cite the source papers for any textstat functions. For example, for `textstat.flesch_reading_ease()`:

> Kincaid, J. Peter, et al. "Derivation of new readability formulas (automated readability index, fog count and flesch reading ease formula) for navy enlisted personnel." (1975).

There is the [The Journal of Open Source Software](https://joss.theoj.org/) where it's a possibility of submitting textstat. @shivam5992, is this something you'd be interested in?

---

If you're looking for open-source collaborators, I would suggest looking over [How to attract new contributors to your open source project](https://medium.freecodecamp.org/46f8b791d787) and [What should I add to readme on GitHub repo to get more open-source contributors?](https://www.quora.com/What-should-I-add-to-readme-on-GitHub-repo-to-get-more-open-source-contributors).

For open-source there's no need to 'cite' textstat, but including textstat in your _setup.py_, _requirements.txt_, or [_Pipfile_](https://pipenv.readthedocs.io/en/latest/) shows that textstat is a dependency of your project.

**Comment by russelljjarvis** [comment]
Absolutely! I think this a great target journal for text-stat, and the Science Accessibility project.

**Comment by russelljjarvis** [comment]
qoute: "If you're looking for open-source collaborators, I would suggest looking over [How to attract new contributors to your open source project](https://medium.freecodecamp.org/46f8b791d787) and [What should I add to readme on GitHub repo to get more open-source contributors?](https://www.quora.com/What-should-I-add-to-readme-on-GitHub-repo-to-get-more-open-source-contributors)." Thanks, I think these are great resources, I will work on a code of conduct, and software hierarchy diagram.

**Comment by shivam5992** [comment]
Hey @alxwrd 

I agree with you. 

https://joss.theoj.org/ is the best place to cite.

**Comment by alxwrd** [comment]
@shivam5992 Excellent. I'll go through their requirements to submit, and get textstat ready!

**Comment by russelljjarvis** [comment]
I am glad you guys are going to publish textstat on JOSS. I don't think publication should exclude non-academic researchers.

I have since implemented some of the major points in the recommendations from:  [How to attract new contributors to your open source project](https://medium.freecodecamp.org/46f8b791d787) and [What should I add to readme on GitHub repo to get more open-source contributors?](https://www.quora.com/What-should-I-add-to-readme-on-GitHub-repo-to-get-more-open-source-contributors)." 

I think there is at least one actual text-stat feature, that adds innovation, to the exercise of measuring reading level complexity. 

I think the 'standard' measure you implemented is really necessary for the web scrapping exercise, I describe in the [science accessibility web scraping project](https://github.com/russelljjarvis/ScienceAccessibility/blob/dev/README.md)


Using just one type of reading level calculator per document, seemed to give biased and un-intuitive results for many documents.

To fit with intuition, the [post modern essay generator ](http://www.elsewhere.org/pomo/) (PMEG) should give really high reading grade scores (as its machine generated obfuscated non-sense), and the upgoer5 should have low reading level. I can't remember the exact details, but I think all algorithms correctly identify the upgoer5 library as low complexity, but I feel that many do not penalize the PMEG enough. I think the standard gave the best result.

**Comment by russelljjarvis** [comment]
Do you guys want to collaborate in one paper, where you guys can be first authors? I think I could contribute lots of plots, data, and motivations for the application of your work.

**Comment by shivam5992** [comment]
@russelljjarvis .. can you share some more details about the paper?

**Comment by russelljjarvis** [comment]
Is it okay if I PM you about it at the email address associated with your GitHub account? Generally, it's about using textstat combined with sentiment analysis to evaluate the accessibility of traditional science, versus pseudoscience, and parascience (like the Wikipedia, and the quantified self writings).

**Comment by alxwrd** [comment]
I'm going to close this for now. I haven't had the time to look into submitting textstat to joss. I might consider going through the process in the future.

**Comment by russelljjarvis** [comment]
No probs. I am still actively pursing this.
