### ISSUE TITLE
textstat measures not easily cast to int/float.

### ISSUE THREAD

**Issue by russelljjarvis** [shivam5992/textstat#80]
I wonder, if its okay if I edit the textstat code so it has an attribute that is an numeric type, in order to avoid the need for performing the following operation:
https://github.com/russelljjarvis/ScienceAccessibility/blob/dev/SComplexity/t_analysis.py#L135-#L138

```
            standard_  = textstat.text_standard(corpus)
            try:
                urlDat['standard']  = float(standard_[0:2])
            except:
                urlDat['standard']  = float(standard_[0:1])
```

**Comment by alxwrd** [comment]
Hey @russelljjarvis. You should be able to get the result you need by specifying the keyword augment `float_output`.

```python
textstat.text_standard(corpus, float_output=True)
```
