### ISSUE TITLE
flesch_reading_ease(test_data) does not work, even though I followed the method 

### ISSUE THREAD

**Issue by repunzel123** [shivam5992/textstat#83]
this is my code

```python
import textstat
test_data = (
    "Playing games has always been thought to be important to "
    "the development of well-balanced and creative children; "
    "however, what part, if any, they should play in the lives "
    "of adults has never been researched that deeply. I believe "
    "that playing games is every bit as important for adults "
    "as for children. Not only is taking time out to play games "
    "with our children and other adults valuable to building "
    "interpersonal relationships but is also a wonderful way "
    "to release built up tension."
)
textstat.flesch_reading_ease(test_data)
```

but what I got in the screen is
```
AttributeError: module 'textstat' has no attribute 'flesch_reading_ease'
```

I don't think my code is wrong, I saw the similar problem in a closed issues, but do not know why this happy again and how to deal with it

**Comment by alxwrd** [comment]
hi @repunzel123 :wave: 

Thanks for raising this.

Could you let me know what version of textstat you have installed?

```
python -m pip show textstat
```

You will need greater than 0.5 installed. If not, you can upgrade by

```
python -m pip install textstat -U
```

For previous versions you will need to import textstat like so:
```python
from textstat.textstat import textstat
```

**Comment by repunzel123** [comment]
Hi alxwrd
Thank you very much for your quick reply. I am afraid that the problem still exists. I type the "python -m pip show textstat" in CMD, but nothing come up, and I also did it on spyder, then it shows  invalid syntax. I do not know the version, but I do not think it is the old version, because when I use "from textstat.textstat import textstat" instead, the screen shows this "ModuleNotFoundError: No module named 'textstat.textstat'; 'textstat' is not a package".
Also, I did try to upgrade the textstat by using the code you gave me, but I get "command python setup.py egg_info failed with error code 1 windows". I follow advice from this website, to upgrade the setuptools, but when I try to upgrade setup tools, cmd shows "Requirement already up-to-date....."

Sorry for that, but could you please help?

Thank you so much

**Comment by alxwrd** [comment]
@repunzel123 no worries.

Can you let me know what the output of the following is:
```python
import textstat
print(dir(textstat))
print(textstat.__version__)
```

Are you using a Python distibution (e.g. Anaconda)?

And, how did you install textstat?

**Comment by repunzel123** [comment]
Hi alxwrd
Thank you for your reply.
The output is
import textstat
print(dir(textstat))
print(textstat.__version__)
['Counter', 'Pyphen', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', '__warningregistry__', 'division', 'easy_word_set', 'get_grade_suffix', 'legacy_round', 'math', 'operator', 'pkg_resources', 'print_function', 're', 'repoze', 'string', 'textstat', 'textstatistics']
Traceback (most recent call last):

  File "<ipython-input-30-4d9c19867391>", line 3, in <module>
    print(textstat.__version__)

AttributeError: module 'textstat' has no attribute '__version__'

Yes, I am using Anaconda, or should I say Spyder

I remember I download the textstat file from "https://pypi.org/project/textstat/#files" or "https://github.com/shivam5992/textstat", and put one of the file, under C:\Users\myname\.spyder-py3.
Then open cmd, type"pip install textstat". I am not sure whether it is correct or not, but at least the now screen does not show that it could not found textstat, so I assume the installation is successful.

But I found a strange thing, I want to reinstall textstat again, I open cmd and type"pip install textstat", the cmd shows an error"
Command "python setup.py egg_info" failed with error code 1 in C:\Users\LIURUO~1\AppData\Local\Temp\pip-install-fkpjdugz\textstat\
I am sure my setup tools are updated but I could not solve this error.

I wonder does this cause my original problem?

Thank you so much for your time.

**Comment by alxwrd** [comment]
@repunzel123 I'm going to close this issue as I think it's an installation issue, and not an issue with textstat itself.

However, this doesn't mean I think _your_ issue is resolved. If you're still having issues, feel free to ask more here. ✨
