### ISSUE TITLE
Question about the code correctness? PDF text extraction and readability index(gunning fog) 

### ISSUE THREAD

**Issue by repunzel123** [shivam5992/textstat#85]
Hi everyone
I am doing a readability (fog index) to a PDF (academic paper). I extract the text of PDF (all pages) and then I try to transfer the context direct into readability code. But I do not think I am correct, because the index I got is 9.69, which is too low I think. I use the example in Github, much easier one, and got 12. Can anyone help me to check the code? many thanks

```python
import PyPDF2
pdfName = "C:\\Users\\Liuruohan\\.spyder-py3\\peer.pdf"
read_pdf = PyPDF2.PdfFileReader(pdfName)

for i in range(read_pdf.getNumPages()):
    page = read_pdf.getPage(i)
    print ('Page No - ' + str(1+read_pdf.getPageNumber(page)))
    page_content = page.extractText()
    print (page_content)

import textstat
test_data = page_content
textstat.gunning_fog(test_data)
```

#I do not know what should I put behind the test_data, and is my first part correct?(I want to extract text from all pages)#

Many thanks

**Comment by alxwrd** [comment]
hi @repunzel123 

With your current code, you're overriding the value in `page_content`, not adding to it. So, I expect you are getting a score based on the last page.

```python
import PyPDF2
import textstat

pdf_name = "C:\\Users\\Liuruohan\\.spyder-py3\\peer.pdf"
pdf_file = PyPDF2.PdfFileReader(pdfName)

file_content = ""

for page in pdf_file.pages:
    file_content += page.extractText()

textstat.gunning_fog(file_content)
```

**Comment by repunzel123** [comment]
Hi alxwrd
Thank you so much. I use your code and I get 21 for this academic paper, and I think it works. But just two more questions
1. for "file_content += page.extractText()" what does "+=" means? I searched the internet and found some say, it means a +=  b equals a + a =b, but I do not know how it was apply to this case.
2. If I wish to extract text from certain pages, (page 3-page 11)what adjustment should I do? using "range" and "PageNum"?

Thank you very much

**Comment by alxwrd** [comment]
hi @repunzel123 

### 1
In Python you can add two strings together by using the `+` operator. So,
```python
>>> a = "Hello " + "world"
>>> print(a)
Hello world
```
So for each iteration of the `for` loop, it is adding `page.extractText()` to what is already in `file_content`.

So with the example expanded out:

```python
file_content = ""

for page in pdf_file.pages:
    file_content = file_content + page.extractText()
```

### 2

Yes I would probaly just use `range()` to get a subset of pages.

```python
file_content = ""

for page_num in range(3, 12):
    page = pdf_file.getPage(page_num)
    file_content += page.extractText()
```

**Comment by repunzel123** [comment]
Thank you for your reply, it is very helpful!!!
