### ISSUE TITLE
text-stat standard (label documentation).

### ISSUE THREAD

**Issue by russelljjarvis** [shivam5992/textstat#88]
text-stat `standard` can attain very high values ie 40 or more. Since the standard metric is probably no longer informative about reading level, do you think it makes sense to describe it as a measure of 'cognitive-load' associated with decoding the text? 
See 1st plot of distributions here:
https://github.com/russelljjarvis/ScienceAccessibility

**Comment by alxwrd** [comment]
@russelljjarvis I don't know if it would be fair to describe the scores as a 'cognitive-load'.

If someone has a reading level of 'university' reads a text rated for small children, yes there would be very little cognitive-load. However, if a small child read the same text that's rated for them, the cognitive-load would be average.
